# Generated by Django 3.2.3 on 2021-05-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posterimage',
            name='images',
            field=models.FileField(upload_to='media/'),
        ),
    ]
