# Generated by Django 3.2.3 on 2021-05-28 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_posterimage_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='size',
        ),
    ]
