# Generated by Django 3.2.3 on 2021-06-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_poster_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='new_arrivals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
